// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_3_X7trkoqZMIBxRFXpr0VkaRPkyDns',
    appId: '1:707213168000:web:2c5d2fb2f965e84010c565',
    messagingSenderId: '707213168000',
    projectId: 'gemeye-app-2026',
    authDomain: 'gemeye-app-2026.firebaseapp.com',
    storageBucket: 'gemeye-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJ8adi4kMqFWiljz3LP9YlQgNWWz4uds',
    appId: '1:707213168000:android:fa1eca1a8338c69410c565',
    messagingSenderId: '707213168000',
    projectId: 'gemeye-app-2026',
    storageBucket: 'gemeye-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtPqZ2A02ZyCkrXxk2Zb8iS_HIfi5Vdg',
    appId: '1:707213168000:ios:79d1f3397805f77710c565',
    messagingSenderId: '707213168000',
    projectId: 'gemeye-app-2026',
    storageBucket: 'gemeye-app-2026.firebasestorage.app',
    iosClientId: '707213168000-mi3q9a9l182pf56kvip8tomhednup5ks.apps.googleusercontent.com',
    iosBundleId: 'com.gemeye.gemeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtPqZ2A02ZyCkrXxk2Zb8iS_HIfi5Vdg',
    appId: '1:707213168000:ios:79d1f3397805f77710c565',
    messagingSenderId: '707213168000',
    projectId: 'gemeye-app-2026',
    storageBucket: 'gemeye-app-2026.firebasestorage.app',
    iosClientId: '707213168000-mi3q9a9l182pf56kvip8tomhednup5ks.apps.googleusercontent.com',
    iosBundleId: 'com.gemeye.gemeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_3_X7trkoqZMIBxRFXpr0VkaRPkyDns',
    appId: '1:707213168000:web:0793cd536ce5beb610c565',
    messagingSenderId: '707213168000',
    projectId: 'gemeye-app-2026',
    authDomain: 'gemeye-app-2026.firebaseapp.com',
    storageBucket: 'gemeye-app-2026.firebasestorage.app',
  );
}
