"""Certificates (Phase 4b) and the public verification endpoint.

cert_no is GE-YYYYMM-NNNNN (Asia/Colombo month, counter "cert-YYYYMM"). The verify
link carries a random token; the public endpoint needs both, and an unknown number
or a wrong token give the same 404."""
import hashlib
import logging
import re
import secrets
from typing import Optional
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, File, HTTPException, Query, Request, Response, UploadFile
from pymongo.errors import DuplicateKeyError
from slowapi import Limiter
from slowapi.util import get_remote_address

from app.auth import active_user_strict, current_user
from app.db import utcnow
from app.routers import NOT_FOUND, UNAVAILABLE, _decode_cursor, _encode_cursor, get_db, get_storage
from app.schemas import (CertificateIn, CertificateIssued, CertificateItem, CertificateList,
                         PublicCertificate, RevokeIn)

logger = logging.getLogger("gemeye.api")
router = APIRouter()
limiter = Limiter(key_func=get_remote_address)

COLOMBO = ZoneInfo("Asia/Colombo")
VERIFY_BASE_URL = "https://gemeye-app-2026.web.app/v/"
PUBLIC_ORIGINS = ("https://gemeye-app-2026.web.app", "http://localhost:3000")
SLUG = re.compile(r"^(GE-\d{6}-\d{5})-(.+)$")
MAX_PDF_BYTES = 5 * 1024 * 1024
DISCLAIMER = ("Generated by the GemEye automated colour grading system. Not a substitute "
              "for a certified gemological laboratory report.")
WITHDRAWN_REASON = "Owner account deleted"
# Removed when a certificate is withdrawn (account deletion); cert_no, issued_at,
# status, the reason and the token hash stay so old links show "withdrawn".
PRIVATE_FIELDS = ("uid", "grading_id", "token", "snapshot", "owner", "image_key", "pdf_key", "pdf_sha256",
                  "pdf_uploaded_at", "revoked_at")
SNAPSHOT_FIELDS = ("grade", "grade_name", "trade_name", "confidence", "uncertainty", "referred",
                   "colour", "delta_e00_to_typical", "model_version")
_DUMMY_HASH = hashlib.sha256(b"no-such-certificate").hexdigest()


def _sha256(s):
    return hashlib.sha256(s.encode()).hexdigest()


def public_headers(request):
    """Cache-Control and CORS (allowed origins only) for /public/ responses."""
    h = {"Cache-Control": "no-store"}
    origin = request.headers.get("origin")
    if origin in PUBLIC_ORIGINS:
        h.update({"Access-Control-Allow-Origin": origin, "Vary": "Origin"})
    return h


def verify_url(doc):
    return f"{VERIFY_BASE_URL}{doc['_id']}-{doc['token']}"


def certificate_item(doc):
    return {"cert_no": doc["_id"], "verify_url": verify_url(doc),
            **{k: doc.get(k) for k in ("grading_id", "status", "issued_at", "snapshot", "owner",
                                       "pdf_sha256", "pdf_uploaded_at", "revoked_reason",
                                       "revoked_at")}}


def _own_certificate(db, uid, cert_no):
    doc = db.certificates.find_one({"_id": cert_no, "uid": uid})
    if doc is None:
        raise HTTPException(404, NOT_FOUND)
    return doc


def _snapshot(db, grading, now):
    r = grading["result"]
    calibration = None
    sid = grading.get("calibration_session_id")
    if sid:
        cal = db.calibrations.find_one({"uid": grading["uid"], "session_id": sid},
                                       sort=[("created_at", -1)])
        calibration = {"session_id": sid, "residual": cal.get("residual") if cal else None}
    return {"stone_id": grading["stone_id"], **{k: r.get(k) for k in SNAPSHOT_FIELDS},
            "captured_at": grading["created_at"], "issued_at": now, "calibration": calibration}


def _issued(doc):
    return {"cert_no": doc["_id"], "verify_url": verify_url(doc), "issued_at": doc["issued_at"]}


@router.post("/certificates", response_model=CertificateIssued, status_code=201)
def issue_certificate(body: CertificateIn, response: Response, user=Depends(active_user_strict),
                      db=Depends(get_db), storage=Depends(get_storage)):
    """Idempotent: a grading that already has a valid certificate gets it back (200)."""
    uid = user["uid"]
    grading = db.gradings.find_one({"_id": body.grading_id, "uid": uid, "deleted": False})
    if grading is None or grading.get("status") != "ok":
        raise HTTPException(404, NOT_FOUND)
    existing = db.certificates.find_one({"grading_id": grading["_id"], "status": "valid"})
    if existing is not None:
        response.status_code = 200
        return _issued(existing)

    profile = db.ensure_user(uid, user["email"])
    owner = None
    if (profile.get("settings") or {}).get("show_name_on_certificates"):
        owner = {"display_name": profile.get("display_name"),
                 "company": (profile.get("company") or {}).get("name")}
    now = utcnow()
    now = now.replace(microsecond=now.microsecond // 1000 * 1000)   # MongoDB keeps ms
    month = now.astimezone(COLOMBO).strftime("%Y%m")
    seq = db.next_seq(f"cert-{month}")
    if seq > 99999:
        logger.error("Certificate counter for %s is exhausted", month)
        raise HTTPException(500, "Internal server error.")
    token = secrets.token_urlsafe(12)
    doc = {"_id": f"GE-{month}-{seq:05d}", "uid": uid, "grading_id": grading["_id"],
           "token": token, "token_sha256": _sha256(token), "status": "valid", "issued_at": now,
           "snapshot": _snapshot(db, grading, now), "owner": owner,
           "image_key": None, "pdf_key": None, "pdf_sha256": None}
    # The grading's S3 key contains the uid, so the public page links a copy.
    if grading.get("image_key"):
        image_key = storage.certificate_key(doc["_id"], grading["image_key"].rsplit(".", 1)[1])
        try:
            storage.copy(grading["image_key"], image_key)
            doc["image_key"] = image_key
        except Exception:
            logger.exception("S3 certificate image copy failed")
            raise HTTPException(503, UNAVAILABLE)
    try:
        db.certificates.insert_one(doc)
    except DuplicateKeyError:
        if doc["image_key"]:
            storage.delete(doc["image_key"])
        # A concurrent request issued it first.
        existing = db.certificates.find_one({"grading_id": grading["_id"], "status": "valid"})
        if existing is None:
            raise
        response.status_code = 200
        return _issued(existing)
    return _issued(doc)


@router.get("/certificates", response_model=CertificateList)
def list_certificates(limit: int = Query(50, ge=1, le=100), cursor: Optional[str] = None,
                      user=Depends(current_user), db=Depends(get_db)):
    q = {"uid": user["uid"]}
    if cursor:
        t, cid = _decode_cursor(cursor)
        q = {"$and": [q, {"$or": [{"issued_at": {"$lt": t}},
                                  {"issued_at": t, "_id": {"$lt": cid}}]}]}
    docs = list(db.certificates.find(q).sort([("issued_at", -1), ("_id", -1)]).limit(limit + 1))
    more = len(docs) > limit
    docs = docs[:limit]
    return {"items": [certificate_item(d) for d in docs],
            "next_cursor": _encode_cursor({"created_at": docs[-1]["issued_at"],
                                           "_id": docs[-1]["_id"]}) if more else None}


@router.get("/certificates/{cert_no}", response_model=CertificateItem)
def get_certificate(cert_no: str, user=Depends(current_user), db=Depends(get_db)):
    return certificate_item(_own_certificate(db, user["uid"], cert_no))


@router.post("/certificates/{cert_no}/pdf", response_model=CertificateItem, status_code=201)
def upload_pdf(cert_no: str, file: UploadFile = File(...), user=Depends(active_user_strict),
               db=Depends(get_db), storage=Depends(get_storage)):
    """Once only per certificate (409 afterwards). Stored at certificates/{cert_no}.pdf."""
    uid = user["uid"]
    doc = _own_certificate(db, uid, cert_no)
    if doc["status"] != "valid":
        raise HTTPException(409, "Certificate is not valid.")
    if doc.get("pdf_key"):
        raise HTTPException(409, "The PDF has already been uploaded.")
    data = file.file.read(MAX_PDF_BYTES + 1)
    if len(data) > MAX_PDF_BYTES:
        raise HTTPException(413, "PDF is larger than 5 MB.")
    if file.content_type != "application/pdf" or not data.startswith(b"%PDF-"):
        raise HTTPException(400, "File must be a PDF.")
    key = storage.certificate_key(cert_no)
    sha = hashlib.sha256(data).hexdigest()
    # Claim the slot first so two concurrent uploads cannot both write the object.
    claimed = db.certificates.update_one(
        {"_id": cert_no, "uid": uid, "status": "valid", "pdf_key": None},
        {"$set": {"pdf_key": key, "pdf_sha256": sha, "pdf_uploaded_at": utcnow()}})
    if claimed.modified_count == 0:
        raise HTTPException(409, "The PDF has already been uploaded.")
    try:
        storage.put(key, data, "application/pdf")
    except Exception:
        logger.exception("S3 PDF upload failed")
        db.certificates.update_one({"_id": cert_no}, {"$set": {
            "pdf_key": None, "pdf_sha256": None, "pdf_uploaded_at": None}})
        raise HTTPException(503, UNAVAILABLE)
    return certificate_item(db.certificates.find_one({"_id": cert_no}))


@router.post("/certificates/{cert_no}/revoke", response_model=CertificateItem)
def revoke_certificate(cert_no: str, body: RevokeIn, user=Depends(active_user_strict),
                       db=Depends(get_db)):
    """Owner only for now (admin revoke comes in Phase 10)."""
    doc = _own_certificate(db, user["uid"], cert_no)
    if doc["status"] != "valid":
        raise HTTPException(409, "Certificate is not valid.")
    db.certificates.update_one({"_id": cert_no, "status": "valid"}, {"$set": {
        "status": "revoked", "revoked_reason": body.reason.strip(), "revoked_at": utcnow()}})
    return certificate_item(db.certificates.find_one({"_id": cert_no}))


# ---- Public verification (no auth) ----

@router.options("/public/v/{slug}", include_in_schema=False)
def verify_preflight(slug: str, request: Request):
    h = public_headers(request)
    if "Access-Control-Allow-Origin" in h:
        h.update({"Access-Control-Allow-Methods": "GET", "Access-Control-Max-Age": "600"})
    return Response(status_code=204, headers=h)


@router.get("/public/v/{slug}", response_model=PublicCertificate)
@limiter.limit("30/minute")
def verify_certificate(slug: str, request: Request, response: Response, db=Depends(get_db),
                       storage=Depends(get_storage)):
    m = SLUG.match(slug)
    doc = db.certificates.find_one({"_id": m.group(1)}) if m else None
    given = _sha256(m.group(2)) if m else ""
    stored = (doc or {}).get("token_sha256") or _DUMMY_HASH
    if not secrets.compare_digest(stored, given) or doc is None:
        raise HTTPException(404, NOT_FOUND)
    response.headers.update(public_headers(request))

    out = {"cert_no": doc["_id"], "status": doc["status"], "issued_at": doc["issued_at"],
           "revoked_reason": doc.get("revoked_reason"), "disclaimer": DISCLAIMER}
    if doc["status"] == "withdrawn":
        return out
    out.update(snapshot=doc["snapshot"], owner=doc.get("owner"), revoked_at=doc.get("revoked_at"))
    try:
        if doc.get("image_key"):
            out["image_url"] = storage.presigned_get(doc["image_key"])
        if doc.get("pdf_key"):
            out.update(pdf_url=storage.presigned_get(doc["pdf_key"]), pdf_sha256=doc["pdf_sha256"])
    except Exception:
        logger.exception("Presign failed")
    return out
